In [1]:
# import libraries
import numpy as np
import torch

In [18]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

In [19]:
# try some multiplications...
# print(np.round(np.matmul(A,B)))
print(np.round(A@B,2))
print()
print(np.round(C.T@A,2))

[[ 0.9  -1.04 -0.19 -1.43  0.34]
 [-0.4   0.76  0.79  1.06 -0.  ]
 [ 0.23 -0.13  1.11 -1.27 -0.16]]

[[ 0.27  0.48  0.38 -0.57]
 [ 0.61  1.3  -3.33  0.39]
 [-1.37 -1.39  1.87  0.54]
 [ 1.02  0.85 -1.47 -0.24]
 [-0.4   0.07  0.24 -0.03]
 [ 1.05  0.5   0.42 -0.83]
 [ 1.64  1.23 -1.56 -0.64]]


In [20]:
# create some random matrices
D = torch.randn(3,4)
E = torch.randn(4,5)
F1 = np.random.randn(4,7)
F2 = torch.tensor( C1,dtype=torch.float )

In [21]:
# try some multiplications...
print(np.round(D@E,2))
print()
print(np.round(D@F2,2))

tensor([[-0.2000, -1.2000, -0.9300, -2.8300, -0.9700],
        [-0.6600,  1.0900, -0.4700,  1.6200,  1.1600],
        [ 0.8800, -1.4300, -0.6900, -0.7300, -0.8400]])

tensor([[ 2.6300,  1.4300, -1.6000, -0.3900,  1.0100,  1.4700, -2.9700],
        [-2.7000, -2.0400, -0.3000, -0.7700,  1.9100, -3.0800,  0.9100],
        [ 4.1400,  3.0800,  1.7200,  1.0500, -1.0100,  2.3300, -2.0400]])
