In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [6]:
# create a vector
v = np.array([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print('Min: %g, Max: %g' %(minval,maxval) )

# now for the argmin/argmax
minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min index: %g, Max index: %g' %(minidx,maxidx) )

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min: -3, Max: 40
Min index: 3, Max index: 1
Min val is -3, max val is 40


In [12]:
# repeat with matrix
M = np.array([ [0,1,10], 
               [20,8,5] ])
print(M)
print()

# various minima in this matrix!
minvals1 = np.min(M)        # minimum from Entire matrix
minvals2 = np.min(M,axis=0) # minimum of each column (across rows)
minvals3 = np.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]

0
[0 1 5]
[0 5]


In [14]:
# various minima in this matrix!
minidx1 = np.argmin(M)        # minimum from Entire matrix
minidx2 = np.argmin(M,axis=0) # minimum of each column (across rows)
minidx3 = np.argmin(M,axis=1) # minimum of each row (across columns)

# print them out
print(minidx1)
print(minidx2)
print(minidx3)

0
[0 0 1]
[0 2]


In [17]:
# create a vector
v = torch.tensor([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = torch.min(v)
maxval = torch.max(v)

print('Min: %g, Max: %g' %(minval,maxval) )

# now for the argmin/max
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min index: %g, Max index: %g' %(minidx,maxidx) )

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min: -3, Max: 40
Min index: 3, Max index: 1
Min val is -3, max val is 40


In [22]:
# repeat with matrix
M = torch.tensor([ [0,1,10],
                   [20,8,5] ])

print(M)
print()

# various minima in this matrix!
min1 = torch.min(M)        # minimum from Entire matrix
min2 = torch.min(M,axis=0) # minimum of each column (across rows)
min3 = torch.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(min1)
print()
print(type(min2))
print()
print(min2)
print()
print(min2.values)
print(min2.indices)

tensor([[ 0,  1, 10],
        [20,  8,  5]])

tensor(0)

<class 'torch.return_types.min'>

torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))

tensor([0, 1, 5])
tensor([0, 0, 1])
