In [1]:
# import libraries
import numpy as np
import torch

In [4]:
# generate a few random numbers
np.random.randn(5)

# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


In [9]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20260543)

print( randseed1.randn(5) ) # same sequence
print( randseed2.randn(5) ) # different from above, but same each time
print( randseed1.randn(5) ) # same as two up
print( randseed2.randn(5) ) # same as two up
print( np.random.randn(5) ) # different every time

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-2.26989108 -0.19587621 -1.06689663 -0.95039987 -0.42823185]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[-2.49721763  1.69728538 -1.0709443   0.03271105  1.44720732]
[ 0.97754176 -0.13858525  0.10385631  0.30059104  0.9682053 ]


In [13]:
torch.randn(5)

tensor([ 0.0098, -0.1018,  1.4098,  0.0215, -1.4998])

In [21]:
torch.manual_seed(17)
print( torch.randn(5) )

# torch's seed doesn't spread to numpy
print( np.random.randn(5) )

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 0.0991466   0.63792617  0.70311068 -0.91609315 -0.78601423]
